behaviors:
  Ship:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1
      buffer_size: 100
      learning_rate: 1.0e-3
      beta: 5.0e-4
      epsilon: 0.4
      lambd: 0.99
      num_epoch: 5
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 50000
    time_horizon: 64
    summary_freq: 10000
